Review changes

diff --git a/lane.d/google-api-docs-sheets-download b/lane.d/google-api-docs-sheets-download
--- a/lane.d/google-api-docs-sheets-download
+++ b/lane.d/google-api-docs-sheets-download
@@ -1,46 +1,46 @@
 #!/bin/sh
 
-_USAGE() {
+if [ ! -x "$(command -v curl)" ]; then
+  echo "Error: curl is not installed." >&2
+  exit 3
+fi
+
+usage() {
 cat << END
 OPTIONS
     -h show this usage
     -o output path
     -i document id
     -t bearer token, see google-api-jwt-generate
-    -f format, default csv
+    -f format, defaults to csv
 END
 }
 
-unset -v OUTPUT ID TOKEN
-FORMAT='csv'
+unset -v output id token
+format='csv'
 while getopts "hi:t:f:o:" option; do
   case $option in
-    o) OUTPUT="$OPTARG" ;;
-    i) ID="$OPTARG" ;;
-    t) TOKEN="$OPTARG" ;;
-    f) FORMAT="$OPTARG" ;;
+    o) output="$OPTARG" ;;
+    i) id="$OPTARG" ;;
+    t) token="$OPTARG" ;;
+    f) format="$OPTARG" ;;
     \?)
       echo "unknown option: $option"
-      _USAGE
+      usage
       exit 1
       ;;
     h)
-      _USAGE
+      usage
       exit 0
       ;;
   esac
 done
 shift $((OPTIND - 1))
 
-if [ -z "$ID" ] || [ -z "$TOKEN" ] || [ -z "$OUTPUT" ]; then
-    echo "Must provide output path, document id and authentication key."
-    _USAGE
+if [ -z "$id" ] || [ -z "$token" ] || [ -z "$output" ]; then
+    echo "Must provide output path, document id and bearer token."
+    usage
     exit 2
-fi
-
-if [ ! -x "$(command -v curl)" ]; then
-  echo "Error: curl is not installed." >&2
-  exit 3
 fi
 
 DIR=$(mktemp -dq)
@@ -48,9 +48,9 @@ DIR=$(mktemp -dq)
 trap 'set +x; rm -fr $DIR >/dev/null 2>&1' 0
 trap 'exit 2' 1 2 3 15
 
-url=$(printf 'https://docs.google.com/spreadsheets/d/%s/export?exportFormat=%s' "$ID" "$FORMAT")
-header=$(printf 'Authorization: Bearer %s' "$TOKEN")
+url=$(printf 'https://docs.google.com/spreadsheets/d/%s/export?exportformat=%s' "$id" "$format")
+header=$(printf 'Authorization: Bearer %s' "$token")
 
-OUT=$(dirname "$OUTPUT")
-mkdir -p "$OUT"
-curl --silent --fail -L -o "$OUTPUT" --header "$header" "$url"
+output_parent=$(dirname "$output")
+mkdir -p "$output_parent"
+curl --silent --fail -L -o "$output" --header "$header" "$url"
