Simplify arguments (#4)

diff --git a/lane.d/shell-run-github-workflow-tests b/lane.d/shell-run-github-workflow-tests
--- a/lane.d/shell-run-github-workflow-tests
+++ b/lane.d/shell-run-github-workflow-tests
@@ -13,11 +13,44 @@
 #  - Name of a step: Pass
 #  - Name of a failing step: Fail
 
-FILE=$1
+
+_USAGE() {
+cat << END
+OPTIONS
+    -h show this usage
+    -i workflow file
+END
+}
+
+unset -v FILE
+while getopts "hi:" option; do
+    case $option in
+        i) FILE=$OPTARG ;;
+        \?)
+          echo "unknown option: $option"
+          _USAGE
+          exit 1
+          ;;
+        h)
+          _USAGE
+          exit 0
+          ;;
+    esac
+done
+shift $((OPTIND - 1))
+
+if [ ! -f "$FILE" ]; then
+    echo "Must provide a valid path to a GitHub workflow file with script-based tests."
+    if [ -n "$FILE" ]; then
+      printf "Given: %s\n\n" "$FILE"
+    else
+      echo
+    fi
+    _USAGE
+    exit 1
+fi
 
 DIR=$(mktemp -dq)
-
-[ -f "$FILE" ] || { echo "Not a FILE: $FILE"; exit 1; }
 
 rm -fr "${DIR:?}/"* > /dev/null
 mkdir -p "$DIR" > /dev/null
@@ -41,10 +74,15 @@ yq -o json "$FILE" | jq -rc '.jobs | to_entries[] | [{group: .key, groupName: .v
     GROUP=$(printf '%s\n' "$JOB" | jq -rj '.group')
     GROUP_NAME=$(printf '%s\n' "$JOB" | jq -rj '.groupName')
 
-    echo "cd '${DIR}/workspace/'; git reset HEAD --hard > /dev/null; git clean -fdx . > /dev/null; sh '${DIR}/${GROUP}.sh'" >> "$DIR/runner.sh"
-    echo "TOTAL_PASS=\$((TOTAL_PASS+\$(cat ${DIR}/PASS))); TOTAL_FAIL=\$((TOTAL_FAIL+\$(cat ${DIR}/FAIL)))" >> "$DIR/runner.sh"
-    echo "echo; echo '$GROUP_NAME'" > "${DIR}/${GROUP}.sh"
-    echo "GREEN=$'\e[0;32m'; RED=$'\e[0;31m'; NC=$'\e[0m'; PASS=0; FAIL=0" >> "${DIR}/${GROUP}.sh"
+    {
+      echo "cd '${DIR}/workspace/'; git reset HEAD --hard > /dev/null; git clean -fdx . > /dev/null; sh '${DIR}/${GROUP}.sh'"
+      echo "TOTAL_PASS=\$((TOTAL_PASS+\$(cat ${DIR}/PASS))); TOTAL_FAIL=\$((TOTAL_FAIL+\$(cat ${DIR}/FAIL)))"
+    } >> "$DIR/runner.sh"
+
+    {
+      echo "echo; echo '$GROUP_NAME'"
+      echo "GREEN=$'\e[0;32m'; RED=$'\e[0;31m'; NC=$'\e[0m'; PASS=0; FAIL=0"
+    } > "${DIR}/${GROUP}.sh"
 
     I=0
     printf '%s\n' "$JOB" | jq -rc '.script[] | select(.run != null)' | while read -r STEP; do
@@ -66,17 +104,19 @@ yq -o json "$FILE" | jq -rc '.jobs | to_entries[] | [{group: .key, groupName: .v
 
 done
 
-# shellcheck disable=SC2016
-echo 'TOTAL=$((TOTAL_PASS+TOTAL_FAIL))' >> "$DIR/runner.sh"
-# shellcheck disable=SC2016
-printf 'echo; printf "Tests; Total: \033[1m${TOTAL}\033[0m Passes: \033[1m${TOTAL_PASS}\033[0m Fails: \033[1m${TOTAL_FAIL}\033[0m\n"\n' >> "$DIR/runner.sh"
+{
+  # shellcheck disable=SC2016
+  echo 'TOTAL=$((TOTAL_PASS+TOTAL_FAIL))'
+  # shellcheck disable=SC2016
+  printf 'echo; printf "Tests; Total: \033[1m${TOTAL}\033[0m Passes: \033[1m${TOTAL_PASS}\033[0m Fails: \033[1m${TOTAL_FAIL}\033[0m\n"\n'
+} >> "$DIR/runner.sh"
 
 echo ' done!'
 
 printf 'Preparing workspace... '
 mkdir "$DIR/workspace"
-# shellcheck disable=SC2010,SC2046
-cp -r $(ls -1qA . | grep -v .git$ | tr \\n \ ) "$DIR/workspace/"
+tar -c --exclude .git . | tar -x -C "$DIR/workspace/"
+
 cd "$DIR/workspace/"
 git init > /dev/null 2>&1
 git add . > /dev/null
