Add shellcheck

diff --git a/lane.d/shell-run-github-workflow-tests b/lane.d/shell-run-github-workflow-tests
--- a/lane.d/shell-run-github-workflow-tests
+++ b/lane.d/shell-run-github-workflow-tests
@@ -19,8 +19,8 @@ DIR=$(mktemp -dq)
 
 [ -f "$FILE" ] || { echo "Not a FILE: $FILE"; exit 1; }
 
-rm -fr $DIR/* > /dev/null
-mkdir -p $DIR > /dev/null
+rm -fr "${DIR:?}/"* > /dev/null
+mkdir -p "$DIR" > /dev/null
 trap 'set +x; rm -fr $DIR >/dev/null 2>&1' 0
 trap 'exit 2' 1 2 3 15
 
@@ -35,14 +35,14 @@ set -e
 
 printf 'Preparing runnner...'
 
-echo 'TOTAL_PASS=0; TOTAL_FAIL=0' > $DIR/runner.sh
+echo 'TOTAL_PASS=0; TOTAL_FAIL=0' > "$DIR/runner.sh"
 
 yq -o json "$FILE" | jq -rc '.jobs | to_entries[] | [{group: .key, groupName: .value.name, script: .value.steps}] | .[]' | while read -r JOB; do
     GROUP=$(printf '%s\n' "$JOB" | jq -rj '.group')
     GROUP_NAME=$(printf '%s\n' "$JOB" | jq -rj '.groupName')
 
-    echo "cd '${DIR}/workspace/'; git reset HEAD --hard > /dev/null; git clean -fdx . > /dev/null; sh '${DIR}/${GROUP}.sh'" >> $DIR/runner.sh
-    echo "TOTAL_PASS=\$((TOTAL_PASS+\$(cat ${DIR}/PASS))); TOTAL_FAIL=\$((TOTAL_FAIL+\$(cat ${DIR}/FAIL)))" >> $DIR/runner.sh
+    echo "cd '${DIR}/workspace/'; git reset HEAD --hard > /dev/null; git clean -fdx . > /dev/null; sh '${DIR}/${GROUP}.sh'" >> "$DIR/runner.sh"
+    echo "TOTAL_PASS=\$((TOTAL_PASS+\$(cat ${DIR}/PASS))); TOTAL_FAIL=\$((TOTAL_FAIL+\$(cat ${DIR}/FAIL)))" >> "$DIR/runner.sh"
     echo "echo; echo '$GROUP_NAME'" > "${DIR}/${GROUP}.sh"
     echo "GREEN=$'\e[0;32m'; RED=$'\e[0;31m'; NC=$'\e[0m'; PASS=0; FAIL=0" >> "${DIR}/${GROUP}.sh"
 
@@ -53,9 +53,11 @@ yq -o json "$FILE" | jq -rc '.jobs | to_entries[] | [{group: .key, groupName: .v
 
         echo "$RUN" > "${DIR}/${GROUP}.${I}.sh"
 
-        echo "printf ' - ${STEP_NAME}: '" >> "${DIR}/${GROUP}.sh"
-        echo "set +e; sh '${DIR}/${GROUP}.${I}.sh' > messages 2>&1" >> "${DIR}/${GROUP}.sh"
-        echo "if [ \$? -eq 0 ]; then printf \${GREEN}'Pass\n'\${NC}; PASS=\$((PASS+1)); else printf \${RED}'Fail\n'\${NC}; FAIL=\$((FAIL+1)); cat messages; fi;" >> "${DIR}/${GROUP}.sh"
+        {
+          echo "printf ' - ${STEP_NAME}: '"
+          echo "set +e; sh '${DIR}/${GROUP}.${I}.sh' > messages 2>&1"
+          printf "if [ \$? -eq 0 ]; then printf \${GREEN}'Pass\n'\${NC}; PASS=\$((PASS+1)); else printf \${RED}'Fail\n'\${NC}; FAIL=\$((FAIL+1)); cat messages; fi;\n"
+        } >> "${DIR}/${GROUP}.sh"
 
         I=$((I+1))
     done
@@ -64,15 +66,18 @@ yq -o json "$FILE" | jq -rc '.jobs | to_entries[] | [{group: .key, groupName: .v
 
 done
 
-echo 'TOTAL=$((TOTAL_PASS+TOTAL_FAIL))' >> $DIR/runner.sh
-echo 'echo; printf "Tests; Total: \033[1m${TOTAL}\033[0m Passes: \033[1m${TOTAL_PASS}\033[0m Fails: \033[1m${TOTAL_FAIL}\033[0m\n"' >> $DIR/runner.sh
+# shellcheck disable=SC2016
+echo 'TOTAL=$((TOTAL_PASS+TOTAL_FAIL))' >> "$DIR/runner.sh"
+# shellcheck disable=SC2016
+printf 'echo; printf "Tests; Total: \033[1m${TOTAL}\033[0m Passes: \033[1m${TOTAL_PASS}\033[0m Fails: \033[1m${TOTAL_FAIL}\033[0m\n"\n' >> "$DIR/runner.sh"
 
 echo ' done!'
 
 printf 'Preparing workspace... '
-mkdir $DIR/workspace
-cp -r $(ls -1qA . | grep -v .git$ | tr \\n \ ) $DIR/workspace/
-cd $DIR/workspace/
+mkdir "$DIR/workspace"
+# shellcheck disable=SC2010,SC2046
+cp -r $(ls -1qA . | grep -v .git$ | tr \\n \ ) "$DIR/workspace/"
+cd "$DIR/workspace/"
 git init > /dev/null 2>&1
 git add . > /dev/null
 git commit -am "known state" > /dev/null
@@ -82,4 +87,4 @@ trap 'set +x; cd - > /dev/null; rm -fr $DIR >/dev/null 2>&1' 0
 trap 'exit 2' 1 2 3 15
 
 echo 'Executing runner...'
-sh $DIR/runner.sh
+sh "$DIR/runner.sh"
